In [2]:
''' 
NumPy (short for Numerical Python) is a powerful Python library used for numerical and scientific computing. 
It provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical
functions to operate on these arrays efficiently.
'''

import numpy as np

# Define list
arr = [10,20,30]

# Define numpy array : naar
narr = np.array(arr)

print(narr)

[10 20 30]


In [13]:
# Check the type of arr

print(type(arr))

print(type(narr))
print(narr.shape)

<class 'list'>
<class 'numpy.ndarray'>
(3, 3)


In [ ]:
# Checking Dimension of an numpy array
print(narr.ndim)

1


In [12]:
# Create 2D array

arr = [[10,20,30],[40,50,60],[70,80,90]]

narr = np.array(arr)

print(type(narr))
print(narr.ndim)
print(narr.shape)

<class 'numpy.ndarray'>
2
(3, 3)


In [11]:
# Create 3D array


arr = [[[10,20,30],[40,50,60],[70,80,90]]]

narr = np.array(arr)

print(type(narr))
print(narr.ndim)
print(narr.shape)
narr

<class 'numpy.ndarray'>
3
(1, 3, 3)


array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [8]:
# Create a new numpy array of high dimensional space

arr = np.array([1,2,3,4,5,6], ndmin=5)
arr

array([[[[[1, 2, 3, 4, 5, 6]]]]])

In [21]:
''' 
Number of element present in array = 10
reshape array to 5 rows and 2 columns
'''

array = np.array([0,1,2,3,4,5,6,7,8,9])
array.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
array.min(),array.max(),array.sum()

(0, 9, 45)

In [23]:
# Create Two Dimensional array and use Flatten
# flatten() : Convert Multi dimensional array into One dimensional array

array = np.array([[10,20],[30,40],[50,60]])
array.flatten()

array([10, 20, 30, 40, 50, 60])

In [26]:
# tolist() : This will convert numpy array into list
lst = array.tolist()
print(lst)
print(type(lst)) 

[[10, 20], [30, 40], [50, 60]]
<class 'list'>


In [30]:
# Create Zeros and Ones matrix
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
o = np.ones((3,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
e = np.eye(4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# 20 : 5*4
# Using arange function : np.arange(start,stop,step)
array = np.arange(0,20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
narray = array.reshape(5,4)
print(narray.ndim)
narray

2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
# Standerd deviation
narray.std()

5.766281297335398

In [ ]:
# Varriance
narray.var()

33.25

In [3]:
# Create two dimensional array having 6 rows and 5 coloumns

array = np.array(np.arange(1,31))
two_array = array.reshape(6,5)

In [4]:
two_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [5]:
# two_array[start_row:stop_row,start_colm:stop_colm]
two_array[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [6]:
two_array[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [7]:
two_array[5:,-1:]

array([[30]])

In [9]:
two_array[5:,-1:][0][0]

30